### ISSUE TITLE
Display numeric items before alphabetic items

### ISSUE THREAD

**Issue by splorp** [shoesforindustry/kirby-plugins-alphabetise#2]
Would it be possible to add an option where numeric items are listed before alphabetic items?

Currently, the plugin sorts and displays items as follows:

> [A]
> [B]
> [C]
> […]
> [X]
> [Y]
> [Z]
> [0]
> [1]
> [2]
> […]

I would prefer the output to be listed like this:

> [0]
> [1]
> [2]
> […]
> [A]
> [B]
> [C]
> […]
> [X]
> [Y]
> [Z]

**Comment by shoesforindustry** [comment]
Hi, thanks for the idea, version 0.0.9 now has the option of an 'orderby' key, which essentially sets the sort_flags for ksort. So you can set it as below for numbers first.

``` php
<?php $alphabetise = alphabetise($page->children()->visible()->sortby('title'), array('key' => 'title', 'orderby'=>SORT_STRING))); ?>
```

Hope this helps?

**Comment by splorp** [comment]
Thanks, Russ. I’ll give this a try.
