### ISSUE TITLE
Add support for Kirby 3

### ISSUE THREAD

**Issue by paulrobertlloyd** [shoesforindustry/kirby-plugins-alphabetise#4]
I think given the simple nature of this plugin, all this requires is renaming `alphabetise.php` to `index.php`. That’s what I’ve done locally, and it all seems to work fine.

**Comment by splorp** [comment]
This is great news. Thanks for looking into this, Paul.

**Comment by shoesforindustry** [comment]
Hi Paul, I've not really got around to looking at Kirby 3 yet, but as you say, it's a simple function so given that a file name change is required for the plugin entry point, it should work. Of course the install and documentation may need to change... but I won't be able to get to that for some time.

**Comment by paulrobertlloyd** [comment]
@shoesforindustry Yup, I understand. Thought it was worth noting and adding to the roadmap, as it were. Personally, I think I’ll move the `alphabetise` function into my own collection of functions.

**Comment by shoesforindustry** [comment]
Should work with K3 now
