### ISSUE TITLE
Sort only by letters or only by numbers

### ISSUE THREAD

**Issue by NahuelGerthVK** [shoesforindustry/kirby-plugins-alphabetise#5]
Hi first of all thanks for the beautiful plugin. I managed to update it to Kirby 3 with the description in the Pull requests.

I wanted to ask if it is possible to get an array containing only pages starting with letters and a separate array only with pages starting with numbers.

The goal would be to have an index view of all letters followed by a section for all numbers (all in one section not split by by different numbers).

Thanks a lot :-)

**Comment by splorp** [comment]
> “I managed to update it to Kirby 3 with the description in the Pull requests.”

@NahuelGerthVK Could you please post a link to this information?

I’m migrating a K2 site to K3 very soon and will definitely need this plugin to be working correctly. Thanks!

**Comment by NahuelGerthVK** [comment]
@splorp I simply renamed alphabetise.php to index.php, no guarantees though :-)

https://github.com/shoesforindustry/kirby-plugins-alphabetise/issues/4

**Comment by splorp** [comment]
@NahuelGerthVK Thank you. I completely forgot about that solution … and I had already replied to it.

**Comment by shoesforindustry** [comment]
Yes, renaming to index.php will work and the sorting will also work correctly. I've updated the plugin and docs to reflect this. Thank you for both your input.

**Comment by shoesforindustry** [comment]
> I wanted to ask if it is possible to get an array containing only pages starting with letters and a separate array only with pages starting with numbers.
> 
> The goal would be to have an index view of all letters followed by a section for all numbers (all in one section not split by by different numbers).
> 
> Thanks a lot :-)

[NahuelGerthVK](https://github.com/NahuelGerthVK) not sure what you are after? The plugin as is lists either letters first or numbers depending on the 'orderby'? Can you explain a bit further?

**Comment by NahuelGerthVK** [comment]
Hi @shoesforindustry and thanks for the update and reply.

The goal would be to create the first letter each as capital (which worked fine) but not for the numbers. Instead I wanted to list all subpages starting with numbers in the end under one section (without capital letter).

<img width="225" alt="Bildschirmfoto 2022-02-23 um 13 04 20" src="https://user-images.githubusercontent.com/35173372/155317164-388dbbe7-b423-4715-859e-2f42a1fe8223.png">

**Comment by shoesforindustry** [comment]
Hi [NahuelGerthVK](https://github.com/NahuelGerthVK), I think I see what you mean. In this case it might be best to use this plugin to do the first part, filtering out all titles that are not numbers? And then for the second part just run through them in a loop (without the plugin), with all titles that are numbers listing and sorting as you see fit? Or have I misunderstood?

**Comment by NahuelGerthVK** [comment]
Hi @shoesforindustry yes that might be it. 

I just couldn't figure out how to filter only titles that are not numbers. 

If I take this:

`<?php $alphabetise = alphabetise($page->children()->listed()->sortby('title'), array('key' => 'title')); ?>`

it will filter every title no matter if it begins with a letter or number, right?

**Comment by shoesforindustry** [comment]
Hi @NahuelGerthVK, perhaps with a 'filterBy' regex? The code below could cause problems if the 'text' titles contain numbers... or the 'number' title contain text. But regex is pretty flexible and this is only an example :)

1. Regex for titles with numbers in them
```php
<?php $alphabetise = alphabetise($page->children()->listed()->sortby('title')->filterBy('title', '*', '~[0-9]~'), array('key' => 'title')); ?>
```
2. Regex for titles without numbers in them
```php
<?php $alphabetise = alphabetise($page->children()->listed()->sortby('title')->filterBy('title', '!*' ,'~[0-9]~'), array('key' => 'title')); ?>
```

Does that sound like it could work? Let me know and I will close this issue.

**Comment by NahuelGerthVK** [comment]
@shoesforindustry Thank you so much this worked perfectly!
